# Name: test_aks_vpa.yaml
# Owner: Saurav Mitra
# Description: This yaml config will Test Vertical Pod Autoscaler in AKS Cluster

# Deployment Manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-vpa-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-vpa
  template:
    metadata:
      labels:
        app: test-vpa
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: test-vpa
          image: registry.k8s.io/ubuntu-slim:0.1
          command: ["/bin/sh"]
          args:
            - "-c"
            - "while true; do timeout 0.5s yes >/dev/null; sleep 0.5s; done"
          resources:
            requests:
              cpu: 100m
              memory: 50Mi

---

# VerticalPodAutoscaler Manifest
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: test-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-vpa-deploy
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: 
          - cpu
          - memory
        minAllowed:
          cpu: 100m
          memory: 50Mi
        maxAllowed:
          cpu: 1
          memory: 500Mi
